# Site
name: "테스트"
title: "테스트"
description: "우리가 매일 쓰는 서비스, 어떻게 만들었을까를 파헤치는 기술 블로그"
favicon: 'assets/images/favicon.ico'
url: "https://kyeonkim.github.io"
baseurl: ""
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  kyeonkim:
    name: kyeonkim
    display_name: kyeonkim
    avatar: 'assets/images/avatar.png'
    email: kyeonkim5021@gmail.com
    web: https://github.com/kyeonkim
    description: "\"어떻게 만들었을까\" 시리즈를 연재합니다."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, docs, vendor]
