# Site
name: "step by step"
title: "step by step"
description: "한 걸음씩 만들며 배웁니다"
favicon: 'assets/images/favicon.ico'
url: "https://kyeonkim.github.io"
baseurl: ""
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  kyeonkim:
    name: kyeonkim
    display_name: kyeonkim
    avatar: 'assets/images/avatar.png'
    email: kyeonkim5021@gmail.com
    web: https://github.com/kyeonkim
    description: "안녕하세요."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, docs, vendor]
